# Generated by Django 5.1.7 on 2025-03-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_rating_unique_together_rating_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
